---
title: "`r params$report_title`"
author: "`r params$report_author`"
date: "`r params$report_time`"
output:
  html_document:
    toc: True
params:
  report_title: "Show transcript boundary coverage stats for a single sample"
  report_author: "Anonymus"
  report_time: !r format(Sys.Date(), format="%d/%m/%Y")
  genome_annotation: "s3://encode-public/2019/06/04/8f6cba12-2ebe-4bec-a15d-53f498979de0/gencode.v29.primary_assembly.annotation_UCSC_names.gtf.gz"
  input_path: "ENCFF465VPI.bed"
---

## Setup

```{r}
library(dplyr)
library(tidyr)
library(RCAS)
library(GenomicRanges)
library(GenomicFeatures)
library(ggplot2)
library(ggsci)
```

## Parse genome annotation

```{r}
remove_gtf <- FALSE
genome_annotation_gtf <- params$genome_annotation
if (substr(params$genome_annotation, 1, 5) == "s3://") {
  genome_annotation_gtf <- "tmp_gtf.gtf.gz"
  remove_gtf <- TRUE
  system(
    paste(
      "aws s3 cp", params$genome_annotation,
      genome_annotation_gtf, "--no-sign-request", sep=" "
    ),
    intern=FALSE
  )
}
```

```{r}
genome_range_features <- importGtf(genome_annotation_gtf)
txdb_features <- getTxdbFeaturesFromGRanges(genome_range_features)
```

## Show features

```{r}
sample_bed <- importBed(filePath=params$input_path, sampleN=5000)
```

```{r}
summary <- summarizeQueryRegions(queryRegions = sample_bed, txdbFeatures = txdb_features)
```

```{r}
N_features = length(sample_bed)
summary %>%
  data.frame() %>%
  mutate(
    percent = round((count / N_features), 3) * 100
  ) %>%
  tibble::rownames_to_column("feature") %>%
  ggplot(aes(x = reorder(feature, -percent), y = percent)) + 
  geom_bar(stat = 'identity', aes(fill = feature)) + 
  geom_label(aes(y = percent + 3), label = count) + 
  labs(x = 'transcript feature', y = paste0('percent overlap (n = ', N_features, ')')) + 
  scale_fill_npg() +
  theme_bw(base_size = 14) + 
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
range_overlaps <- as.data.table(queryGff(queryRegions = sample_bed, gffData = genome_range_features))
```

```{r}
biotype_col <- grep('gene_type', colnames(range_overlaps), value = T)
df <- range_overlaps[,length(unique(queryIndex)), by = biotype_col]
colnames(df) <- c("feature", "count")
df$percent <- round(df$count / N_features * 100, 1)
df <- df[order(count, decreasing = TRUE)]
ggplot2::ggplot(df, aes(x = reorder(feature, -percent), y = percent)) + 
  geom_bar(stat = 'identity', aes(fill = feature)) + 
  geom_label(aes(y = percent + 0.5), label = df$count) + 
  labs(x = 'transcript feature', y = paste0('percent overlap (n = ', N_features, ')')) + 
  theme_bw(base_size = 14) + 
  theme(axis.text.x = element_text(angle = 90))
```

## Feature Boundary Coverage Profile

```{r}
cvgList <- calculateCoverageProfileList(
  queryRegions = sample_bed,
  targetRegionsList = txdb_features,
  sampleN = 10000
)
```


```{r}
cvgList %>%
  ggplot(aes(x = bins, y = meanCoverage)) + 
  geom_ribbon(
    fill = 'lightgreen', aes(
      ymin = meanCoverage - standardError * 1.96,
      ymax = meanCoverage + standardError * 1.96
    )
  ) + 
  geom_line(color = 'black') +
  theme_bw(base_size = 14) +
  facet_wrap( ~ feature, ncol = 3) 
```

