---
title: "`r params$report_title`"
author: "`r params$report_author`"
date: "`r params$report_time`"
output:
  html_document:
    toc: True
params:
  report_title: "Get start site of genes and create bins for histogram"
  report_author: "Anonymus"
  report_time: !r format(Sys.Date(), format="%d/%m/%Y")
  genome_annotation: "s3://encode-public/2019/06/04/8f6cba12-2ebe-4bec-a15d-53f498979de0/gencode.v29.primary_assembly.annotation_UCSC_names.gtf.gz"
---

## Setup

```{r}
library(dplyr)
library(tidyr)
library(tibble)
library(RCAS)
library(GenomicRanges)
library(GenomicFeatures)
library(ggplot2)
library(ggsci)
```

## Parse genome annotation

```{r}
remove_gtf <- FALSE
genome_annotation_gtf <- params$genome_annotation
if (substr(params$genome_annotation, 1, 5) == "s3://") {
  genome_annotation_gtf <- "tmp_gtf.gtf.gz"
  remove_gtf <- TRUE
  system(
    paste(
      "aws s3 cp", params$genome_annotation,
      genome_annotation_gtf, "--no-sign-request", sep=" "
    ),
    intern=FALSE
  )
}
```

```{r}
genome_range_features <- importGtf(genome_annotation_gtf)
txdb_features <- getTxdbFeaturesFromGRanges(genome_range_features)
if (remove_gtf) unlink(genome_annotation_gtf)
```

## Filter first exons

```{r}
firstexons <- txdb_features$exons[txdb_features$exons$exon_rank == 1]
firstexons <- firstexons[strand(firstexons) == "+"]
head(firstexons)
```
```{r}
full_gtf <- read.table("gencode.gtf", sep="\t")
head(full_gtf)
```


```{r}
rtracklayer::export(firstexons, "rt_tmp.gtf")
exon_data <- read.table("rt_tmp.gtf", sep="\t")
head(exon_data)
```

```{r}
hijack_gtf <- exon_data %>%
  mutate(
    WINDOW = purrr::map(V4, function(x) seq(0, 4000, 50))
  ) %>%
  unnest(WINDOW) %>%
  mutate(
    V2 = "GENCODE_BIN",
    V3 = "exon",
    V4 = V4 + 2000 - WINDOW,
    V5 = V4 + 50,
    V4 = as.character(V4),
    V5 = as.character(V5),
    EXID = stringr::str_extract(V9, "exon_id \\d+; exon_name .*; exon_rank \\d+; "),
    V9 = paste(EXID, "gene_name Pos", WINDOW - 2000, ";", sep="")
  ) %>%
  dplyr::select(-WINDOW, -EXID)
```

```{r}
write.table(hijack_gtf, "encode_bins.gtf", quote=FALSE, col.names=FALSE, row.names=FALSE, sep="\t")
```

## Process featureCounts#

```{r}
binned_gtf <- read.table("encode_bins.gtf", sep="\t")
head(binned_gtf)
```

```{r}
position_counts <- "/home/rstudio/local_files/counts" %>%
  dir(full.names=TRUE) %>%
  setNames(., gsub("\\.markup.*", "", basename(.))) %>%
  purrr::map(function(x) {
    x %>%
      read.table() %>%
      .[-1, c(1, 7)]
  }) %>%
  bind_rows(.id="Sample") %>%
  mutate(
    Sample = gsub("_counts.*", "", Sample)
  ) %>%
  dplyr::rename(Position = V1, Count = V7) %>%
  mutate(
    Condition = gsub("_R\\d+", "", Sample),
    Count = as.numeric(Count),
    Position = as.numeric(gsub("Pos", "", Position))
  ) %>%
  group_by(Sample) %>%
  mutate(Full_depth = sum(Count, na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(
    Coverage = Count/Full_depth
  ) %>%
  dplyr::select(-Full_depth)
```

```{r}
position_counts <- "/home/rstudio/local_files/binned_multicounts.csv" %>%
  read.csv() %>%
  pivot_longer(-Position) %>%
  dplyr::rename(
    Sample = name,
    Count = value
  ) %>%
  mutate(
    Sample = gsub("_counts.*", "", Sample),
    Condition = gsub("_R\\d+", "", Sample),
    Count = as.numeric(Count),
    Position = as.numeric(gsub("Pos", "", Position))
  ) %>%
  dplyr::filter(Position > -2000, Position < 2000) %>%
  group_by(Sample) %>%
  mutate(Full_depth = sum(Count, na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(
    Coverage = Count/Full_depth
  ) %>%
  dplyr::select(-Full_depth)

head(position_counts)
```

```{r}
pos_labs <- position_counts$Position %>%
  unique() %>%
  .[order(.)] %>%
  paste("c", ., sep="")

position_counts <- position_counts %>%
  mutate(
    Position_c = paste("c", Position, sep=""),
    Position_c = factor(Position_c, levels=pos_labs)
  )
```

```{r}
position_counts %>%
  ggplot(aes(x=Position_c, y=Count, fill=Condition)) +
  geom_boxplot() +
  scale_fill_npg() +
  theme_bw(base_size=14) +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 0.5, hjust=1)
  ) +
  scale_x_discrete(breaks = levels(position_counts$Position_c)[c(T, rep(F, 4))]) +
  labs(x="")
```

```{r}
position_counts %>%
  ggplot(aes(x=Position_c, y=Coverage, fill=Condition)) +
  geom_boxplot() +
  scale_fill_npg() +
  theme_bw(base_size=14) +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 0.5, hjust=1)
  ) +
  scale_x_discrete(breaks = levels(position_counts$Position_c)[c(T, rep(F, 4))]) +
  labs(x="")
```

```{r}
position_counts %>%
  dplyr::filter(Position > -1000, Position < 500) %>%
  dplyr::filter(Condition %in% c("KO6_27_Sh", "KO6_GFP_Sh")) %>%
  ggplot(aes(x=Position_c, y=Count, fill=Condition)) +
  geom_boxplot() +
  scale_fill_npg() +
  theme_bw(base_size=14) +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 0.5, hjust=1)
  ) +
  scale_x_discrete(breaks = levels(position_counts$Position_c)[c(T, rep(F, 3))]) +
  labs(x="")
```

```{r}
position_counts %>%
  dplyr::filter(Position > -1000, Position < 500) %>%
  dplyr::filter(Condition %in% c("KO6_27_Sh", "KO6_GFP_Sh")) %>%
  ggplot(aes(x=Position_c, y=Coverage, fill=Condition)) +
  geom_boxplot() +
  scale_fill_npg() +
  theme_bw(base_size=14) +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 0.5, hjust=1)
  ) +
  scale_x_discrete(breaks = levels(position_counts$Position_c)[c(T, rep(F, 3))]) +
  labs(x="")
```


```{r}
position_counts %>%
  mutate(
    Position_c = paste("c", Position, sep=""),
    Position_c = factor(Position_c, levels=pos_labs)
  ) %>%
  dplyr::filter(Position > -2000, Position < 2000) %>%
  dplyr::filter(Condition %in% c("KO6_27_Sh", "KO6_GFP_Sh")) %>%
  ggplot(aes(x=Position_c, y=Coverage, fill=Condition)) +
  geom_boxplot() +
  scale_fill_npg() +
  theme_bw(base_size=14) +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 0.5, hjust=1)
  ) +
  labs(x="")
```